server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/springboottest
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
